name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Artifact version (e.g. 1.0.1)

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b

      - name: Publish package
        uses: gradle/gradle-build-action@932abbbe1322c8a76c4fb3b7d277bf831e757a40
        with:
          arguments: ":secrets-gradle-plugin:publishPluginsToGitHub"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_VERSION: ${{ github.event.inputs.version }}
